/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandDetailsCommandIdRouteImport } from './routes/command-details.$commandId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandDetailsCommandIdRoute = CommandDetailsCommandIdRouteImport.update({
  id: '/command-details/$commandId',
  path: '/command-details/$commandId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command-details/$commandId': typeof CommandDetailsCommandIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-details/$commandId': typeof CommandDetailsCommandIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command-details/$commandId': typeof CommandDetailsCommandIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/command-details/$commandId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/command-details/$commandId'
  id: '__root__' | '/' | '/command-details/$commandId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandDetailsCommandIdRoute: typeof CommandDetailsCommandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-details/$commandId': {
      id: '/command-details/$commandId'
      path: '/command-details/$commandId'
      fullPath: '/command-details/$commandId'
      preLoaderRoute: typeof CommandDetailsCommandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandDetailsCommandIdRoute: CommandDetailsCommandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
